name: "Get and Cache Dependencies"
description: "Get the Dependencies and Cache them"
inputs:
 cashing:
  description: "Enable caching of dependencies"
  required: false
  default: "true"
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if:  inputs.cashing == 'true' 
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.cashing != 'true'
      run: npm ci
      shell: bash
